target:
    components:
    -   spectral:
            type: PowerLawSpectralModel
            parameters:
            - {name: index, value: 2.5549376641853416, error: 0.2982383919410344,
                min: 0.5, max: 5.0}
            - {name: amplitude, value: 1.2975797753986047e-11, unit: TeV-1 s-1 cm-2,
                error: 1.9471254047998817e-12, min: 1.0e-13, max: 0.01}
            - {name: reference, unit: TeV, min: 0.0001, max: 100.0}
            ebl_abs: {filename: /home/chaitanya/software/gammapy-datasets/1.3/ebl/ebl_dominguez11.fits.gz,
                redshift: 0.11599999999999999}
